version: '3.8'
services:
  postgres:
    image: postgres:15.3
    # restart: always
    environment:
      POSTGRES_PASSWORD : postgres
      POSTGRES_USER : postgres
      POSTGRES_DB : db_user
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
